name: Lint

on: pull_request

jobs:
  lint_code_base:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: volta-cli/action@v1
      - name: Install linters
        run: npm install prettier eslint eslint-config-prettier eslint-plugin-prettier stylelint stylelint-config-prettier stylelint-config-standard @linthtml/linthtml
      - name: Lint JavaScript files
        run: npm run lint:js
      - name: Lint CSS files
        run: npm run lint:css
      - name: Lint HTML files
        run: npm run lint:html
